apiVersion: v1
kind: Pod
metadata: 
    name: httpserverpod
    labels:
        app: httpserverpod
spec:
    imagePullSecrets:
      - name: NEW-SECRET-NAME
    volumes:
    - name: appdir
      hostPath:
        path: /home/ubuntu/pod_helloworld/test
        type: Directory
    containers:
    - name: httpservercontainer
      image: shubjain26/testimages_flask_hello_world_21.11.15
      ports:
      - containerPort: 8888
      volumeMounts:
      - mountPath: /app/test
        name: appdir

---

apiVersion: v1
kind: Service
metadata: 
    name: httpserverservice
spec:
    type: NodePort
    selector:
      app: httpserverpod
    ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30000
      protocol: TCP
